### ISSUE TITLE
TOP3 nie jest aktualizowane

### ISSUE THREAD

**Issue by kwojno77** [dofranko/tower-of-flaming-blames#30]
Zakładka "TOP3" nie jest aktualizowana. Po zdobyciu rekordowego wyniku 49 punktów (!), nie został on wpisany do zakładki rekordów.

**Comment by dofranko** [comment]
> Po zdobyciu rekordowego wyniku 49 punktów (!), nie został on wpisany do zakładki rekordów.

Jeśli widnieje on na liście Twoich osobistych rozgrywek to nie masz o co się martwić, gdyż wynik jest zapisany w bazie danych i gdy naprawiamy błąd, będzie on widniał na liście leaderboard.

**Comment by adbednarz** [comment]
Przejrzałem bazę danych. Na pierwszy rzut oka wydaję się, że wszystkie Twoje dane są prawidłowo zapisane. Potrzebuję więcej czasu, by dogłębnie zbadać temat.

**Comment by adbednarz** [comment]
@dofranko miał rację i ten bug był spowodowany bugiem #31. Naprawa wspomnianego buga oraz lekka modyfikacja bazdy danych powinna rozwiązać sprawę. Daj znać, czy rzeczywiście tak się stało.

**Comment by kwojno77** [comment]
Figuruję już z rekordem na liście top3, jednak ustanawiając nowy rekord, nie jest on zapisywany do top3. Tym razem były to 33 punkty, a zatem powinienem się znaleźć na 3. miejscu.

**Comment by dofranko** [comment]
@kwojno77 aktualnie obsługiwane jest jedna osoba na leaderboard. Wciąż rozmyślamy, czy zmienić ten system.

**Comment by kwojno77** [comment]
Rozumiem, w takim razie wszystko działa. Zamykam
