### ISSUE TITLE
Wylogowuje aplikację

### ISSUE THREAD

**Issue by kwojno77** [dofranko/tower-of-flaming-blames#31]
Przy przegraniu aplikacja na ułamek sekundy wraca do menu gry, po czym minimalizuje się. Po wznowieniu działania aplikacji jestem wylogowany.

**Comment by dofranko** [comment]
Czy ktoś jeszcze miał taki problem? Dla mnie wszystko działa jak należy, również chyba dla @adbednarz. Potrzebujemy więcej feedbacku.

**Comment by dofranko** [comment]
#30 czy to może być powiązane ze sobą? @adbednarz

**Comment by adbednarz** [comment]
Występuje dziwna zbieżność... Przyjrzę się tej sprawie i dam feedback.

**Comment by dofranko** [comment]
Zrobiłem szybki test:
1. Założyłem nowe konto
2. Rozpocząłem rozgrywkę i "przegrałem" ją.
3. Stało się to co @kwojno77 napisał.

Przyjrzymy się.

**Comment by adbednarz** [comment]
@kwojno77 aplikacja została zmodyfikowana. Możesz dać nam feedback, czy po Twojej stronie wszystko działa teraz w porządku?

**Comment by kwojno77** [comment]
Niestety, aplikacja nadal mnie wylogowuje po przegranej, jednak nie zawsze. (Najczęściej, gdy pobijam rekordy)

**Comment by adbednarz** [comment]
Dziękujemy za odpowiedź zwrotną. Będziemy to dalej testować i poinformujemy Cię, gdy uporamy się z tym problemem.

**Comment by dofranko** [comment]
**u MnIe DzIaŁa**

**Comment by adbednarz** [comment]
I am closing it due to not reporting this bug again for a long time.
